apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer # Tells AWS to provision a real cloud Load Balancer for you
  selector:
    app: node-app # Tells the Service to send traffic to pods matching this label
  ports:
    - protocol: TCP
      port: 80         # The port people will type into their browser (HTTP)
      targetPort: 3000 # The port inside your container where the app lives